-- =====================================================
-- MIGRATION: LOCATIONS AND MEASUREMENTS
-- =====================================================

-- 1. Create LOCATIONS table
CREATE TABLE IF NOT EXISTS locations (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL,
    cep text,
    logradouro text,
    numero text,
    complemento text,
    bairro text,
    cidade text,
    uf text,
    type text DEFAULT 'condominium', -- 'condominium', 'company', 'other'
    user_id uuid REFERENCES auth.users(id) NOT NULL,
    created_at timestamptz DEFAULT now()
);

-- 2. Create LOCATION_MEASUREMENTS table
CREATE TABLE IF NOT EXISTS location_measurements (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    location_id bigint REFERENCES locations(id) ON DELETE CASCADE NOT NULL,
    name text NOT NULL, -- e.g. "Sala - Apto Tipo A"
    largura text,
    altura text,
    quantidade integer DEFAULT 1,
    ambiente text,
    tipo_aplicacao text,
    observacao text,
    created_at timestamptz DEFAULT now()
);

-- 3. Enable RLS
ALTER TABLE locations ENABLE ROW LEVEL SECURITY;
ALTER TABLE location_measurements ENABLE ROW LEVEL SECURITY;

-- 4. Create Policies for LOCATIONS
DROP POLICY IF EXISTS "Users can view their own locations" ON locations;
DROP POLICY IF EXISTS "Users can insert their own locations" ON locations;
DROP POLICY IF EXISTS "Users can update their own locations" ON locations;
DROP POLICY IF EXISTS "Users can delete their own locations" ON locations;

CREATE POLICY "Users can view their own locations" ON locations FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can insert their own locations" ON locations FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can update their own locations" ON locations FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "Users can delete their own locations" ON locations FOR DELETE USING (auth.uid() = user_id);

-- 5. Create Policies for LOCATION_MEASUREMENTS
-- Policies depend on the user having access to the parent location
DROP POLICY IF EXISTS "Users can view measurements of their locations" ON location_measurements;
DROP POLICY IF EXISTS "Users can insert measurements to their locations" ON location_measurements;
DROP POLICY IF EXISTS "Users can update measurements of their locations" ON location_measurements;
DROP POLICY IF EXISTS "Users can delete measurements of their locations" ON location_measurements;

CREATE POLICY "Users can view measurements of their locations" ON location_measurements 
FOR SELECT USING (
    EXISTS (SELECT 1 FROM locations WHERE id = location_measurements.location_id AND user_id = auth.uid())
);

CREATE POLICY "Users can insert measurements to their locations" ON location_measurements 
FOR INSERT WITH CHECK (
    EXISTS (SELECT 1 FROM locations WHERE id = location_measurements.location_id AND user_id = auth.uid())
);

CREATE POLICY "Users can update measurements of their locations" ON location_measurements 
FOR UPDATE USING (
    EXISTS (SELECT 1 FROM locations WHERE id = location_measurements.location_id AND user_id = auth.uid())
);

CREATE POLICY "Users can delete measurements of their locations" ON location_measurements 
FOR DELETE USING (
    EXISTS (SELECT 1 FROM locations WHERE id = location_measurements.location_id AND user_id = auth.uid())
);
