-- Salvamento seguro de medidas entre aparelhos.
-- Cada cliente possui uma revisão canônica, histórico recuperável e escrita
-- atômica com comparação de versão.

CREATE TABLE IF NOT EXISTS public.proposal_option_states (
    client_id bigint PRIMARY KEY REFERENCES public.clients(id) ON DELETE CASCADE,
    organization_id uuid,
    revision bigint NOT NULL DEFAULT 0 CHECK (revision >= 0),
    snapshot jsonb NOT NULL DEFAULT '[]'::jsonb CHECK (jsonb_typeof(snapshot) = 'array'),
    updated_at timestamptz NOT NULL DEFAULT now(),
    updated_by uuid,
    updated_device_id text
);

CREATE TABLE IF NOT EXISTS public.proposal_option_history (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id bigint NOT NULL REFERENCES public.clients(id) ON DELETE CASCADE,
    organization_id uuid,
    revision bigint NOT NULL,
    snapshot jsonb NOT NULL CHECK (jsonb_typeof(snapshot) = 'array'),
    created_at timestamptz NOT NULL DEFAULT now(),
    created_by uuid,
    source_device_id text,
    UNIQUE (client_id, revision)
);

CREATE INDEX IF NOT EXISTS proposal_option_history_client_created_idx
    ON public.proposal_option_history (client_id, created_at DESC);

ALTER TABLE public.proposal_option_states ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.proposal_option_history ENABLE ROW LEVEL SECURITY;

CREATE OR REPLACE FUNCTION public.can_access_proposal_client(target_client_id bigint)
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public, auth
AS $$
    SELECT EXISTS (
        SELECT 1
        FROM public.clients client
        LEFT JOIN public.profiles current_profile
          ON current_profile.id = auth.uid()
        WHERE client.id = target_client_id
          AND (
              client.user_id = auth.uid()
              OR (
                  client.organization_id IS NOT NULL
                  AND client.organization_id = current_profile.organization_id
              )
              OR EXISTS (
                  SELECT 1
                  FROM public.organizations organization
                  JOIN public.organization_members member
                    ON member.organization_id = organization.id
                  WHERE organization.owner_id = client.user_id
                    AND member.user_id = auth.uid()
                    AND member.status = 'active'
              )
          )
    );
$$;

REVOKE ALL ON FUNCTION public.can_access_proposal_client(bigint) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.can_access_proposal_client(bigint) TO authenticated;

DROP POLICY IF EXISTS proposal_option_states_select ON public.proposal_option_states;
CREATE POLICY proposal_option_states_select
ON public.proposal_option_states
FOR SELECT TO authenticated
USING (public.can_access_proposal_client(client_id));

DROP POLICY IF EXISTS proposal_option_history_select ON public.proposal_option_history;
CREATE POLICY proposal_option_history_select
ON public.proposal_option_history
FOR SELECT TO authenticated
USING (public.can_access_proposal_client(client_id));

-- Converte as linhas legadas atuais em uma fotografia inicial, sem removê-las.
INSERT INTO public.proposal_option_states (
    client_id,
    organization_id,
    revision,
    snapshot,
    updated_at,
    updated_by,
    updated_device_id
)
SELECT
    proposal.client_id,
    (array_agg(proposal.organization_id) FILTER (WHERE proposal.organization_id IS NOT NULL))[1],
    1,
    jsonb_agg(
        jsonb_build_object(
            'id', proposal.id,
            'name', proposal.name,
            'measurements', COALESCE(proposal.measurements, '[]'::jsonb),
            'generalDiscount', COALESCE(proposal.general_discount, '{}'::jsonb)
        )
        ORDER BY proposal.id
    ),
    max(proposal.created_at),
    (array_agg(proposal.user_id) FILTER (WHERE proposal.user_id IS NOT NULL))[1],
    'migration'
FROM public.proposal_options proposal
GROUP BY proposal.client_id
ON CONFLICT (client_id) DO NOTHING;

INSERT INTO public.proposal_option_history (
    client_id,
    organization_id,
    revision,
    snapshot,
    created_at,
    created_by,
    source_device_id
)
SELECT
    state.client_id,
    state.organization_id,
    state.revision,
    state.snapshot,
    state.updated_at,
    state.updated_by,
    state.updated_device_id
FROM public.proposal_option_states state
ON CONFLICT (client_id, revision) DO NOTHING;

-- Clientes antigos podem continuar alguns minutos com uma versão em cache do
-- PWA. Essa função combina as inclusões legadas com a fotografia canônica em
-- vez de permitir que um snapshot menor apague medidas já recebidas.
CREATE OR REPLACE FUNCTION public.merge_legacy_proposal_snapshots(
    canonical_snapshot jsonb,
    legacy_snapshot jsonb
)
RETURNS jsonb
LANGUAGE plpgsql
IMMUTABLE
AS $$
DECLARE
    canonical_option jsonb;
    legacy_option jsonb;
    canonical_measurement jsonb;
    merged_option jsonb;
    merged_measurements jsonb;
    result_snapshot jsonb := '[]'::jsonb;
BEGIN
    IF jsonb_typeof(canonical_snapshot) <> 'array' THEN
        canonical_snapshot := '[]'::jsonb;
    END IF;
    IF jsonb_typeof(legacy_snapshot) <> 'array' THEN
        legacy_snapshot := '[]'::jsonb;
    END IF;

    FOR legacy_option IN SELECT value FROM jsonb_array_elements(legacy_snapshot)
    LOOP
        SELECT value INTO canonical_option
        FROM jsonb_array_elements(canonical_snapshot)
        WHERE lower(trim(value->>'name')) = lower(trim(legacy_option->>'name'))
        LIMIT 1;

        merged_measurements := COALESCE(legacy_option->'measurements', '[]'::jsonb);

        IF canonical_option IS NOT NULL THEN
            FOR canonical_measurement IN
                SELECT value
                FROM jsonb_array_elements(COALESCE(canonical_option->'measurements', '[]'::jsonb))
            LOOP
                IF NOT EXISTS (
                    SELECT 1
                    FROM jsonb_array_elements(merged_measurements) legacy_measurement
                    WHERE legacy_measurement->>'id' = canonical_measurement->>'id'
                ) THEN
                    merged_measurements := merged_measurements || jsonb_build_array(canonical_measurement);
                END IF;
            END LOOP;
        END IF;

        merged_option := jsonb_set(legacy_option, '{measurements}', merged_measurements, true);
        result_snapshot := result_snapshot || jsonb_build_array(merged_option);
        canonical_option := NULL;
    END LOOP;

    FOR canonical_option IN SELECT value FROM jsonb_array_elements(canonical_snapshot)
    LOOP
        IF NOT EXISTS (
            SELECT 1
            FROM jsonb_array_elements(legacy_snapshot) legacy_candidate
            WHERE lower(trim(legacy_candidate->>'name')) = lower(trim(canonical_option->>'name'))
        ) THEN
            result_snapshot := result_snapshot || jsonb_build_array(canonical_option);
        END IF;
    END LOOP;

    RETURN result_snapshot;
END;
$$;

CREATE OR REPLACE FUNCTION public.capture_legacy_proposal_snapshot()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, auth
AS $$
DECLARE
    affected_client_id bigint;
    current_revision bigint;
    current_snapshot jsonb;
    legacy_snapshot jsonb;
    merged_snapshot jsonb;
    current_org_id uuid;
BEGIN
    IF current_setting('app.proposal_snapshot_rpc', true) = '1' THEN
        RETURN NULL;
    END IF;

    FOR affected_client_id IN SELECT DISTINCT client_id FROM new_proposal_rows
    LOOP
        PERFORM pg_advisory_xact_lock(affected_client_id);

        SELECT state.revision, state.snapshot, state.organization_id
          INTO current_revision, current_snapshot, current_org_id
        FROM public.proposal_option_states state
        WHERE state.client_id = affected_client_id
        FOR UPDATE;

        SELECT COALESCE(
            jsonb_agg(
                jsonb_build_object(
                    'id', proposal.id,
                    'name', proposal.name,
                    'measurements', COALESCE(proposal.measurements, '[]'::jsonb),
                    'generalDiscount', COALESCE(proposal.general_discount, '{}'::jsonb)
                ) ORDER BY proposal.id
            ),
            '[]'::jsonb
        )
        INTO legacy_snapshot
        FROM public.proposal_options proposal
        WHERE proposal.client_id = affected_client_id;

        merged_snapshot := public.merge_legacy_proposal_snapshots(
            COALESCE(current_snapshot, '[]'::jsonb),
            legacy_snapshot
        );
        current_revision := COALESCE(current_revision, 0) + 1;

        INSERT INTO public.proposal_option_states (
            client_id, organization_id, revision, snapshot,
            updated_at, updated_by, updated_device_id
        )
        VALUES (
            affected_client_id,
            COALESCE(
                current_org_id,
                (SELECT organization_id FROM public.profiles WHERE id = auth.uid())
            ),
            current_revision,
            merged_snapshot,
            now(),
            auth.uid(),
            'legacy-client'
        )
        ON CONFLICT (client_id) DO UPDATE SET
            revision = EXCLUDED.revision,
            snapshot = EXCLUDED.snapshot,
            updated_at = EXCLUDED.updated_at,
            updated_by = EXCLUDED.updated_by,
            updated_device_id = EXCLUDED.updated_device_id;

        INSERT INTO public.proposal_option_history (
            client_id, organization_id, revision, snapshot,
            created_at, created_by, source_device_id
        )
        SELECT
            affected_client_id,
            organization_id,
            revision,
            snapshot,
            updated_at,
            updated_by,
            updated_device_id
        FROM public.proposal_option_states
        WHERE client_id = affected_client_id
        ON CONFLICT (client_id, revision) DO NOTHING;
    END LOOP;

    RETURN NULL;
END;
$$;

DROP TRIGGER IF EXISTS proposal_options_capture_legacy_insert ON public.proposal_options;
CREATE TRIGGER proposal_options_capture_legacy_insert
AFTER INSERT ON public.proposal_options
REFERENCING NEW TABLE AS new_proposal_rows
FOR EACH STATEMENT
EXECUTE FUNCTION public.capture_legacy_proposal_snapshot();

DROP TRIGGER IF EXISTS proposal_options_capture_legacy_update ON public.proposal_options;
CREATE TRIGGER proposal_options_capture_legacy_update
AFTER UPDATE ON public.proposal_options
REFERENCING NEW TABLE AS new_proposal_rows
FOR EACH STATEMENT
EXECUTE FUNCTION public.capture_legacy_proposal_snapshot();

CREATE OR REPLACE FUNCTION public.save_proposal_options_snapshot(
    p_client_id bigint,
    p_snapshot jsonb,
    p_expected_revision bigint,
    p_device_id text DEFAULT NULL
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, auth
AS $$
DECLARE
    current_revision bigint;
    current_snapshot jsonb;
    next_revision bigint;
    current_user_id uuid := auth.uid();
    current_org_id uuid;
    option_value jsonb;
BEGIN
    IF current_user_id IS NULL THEN
        RAISE EXCEPTION 'Sessao nao autenticada';
    END IF;

    IF NOT public.can_access_proposal_client(p_client_id) THEN
        RAISE EXCEPTION 'Cliente nao autorizado';
    END IF;

    IF jsonb_typeof(p_snapshot) <> 'array' THEN
        RAISE EXCEPTION 'Snapshot de medidas deve ser um array';
    END IF;

    PERFORM pg_advisory_xact_lock(p_client_id);

    SELECT state.revision, state.snapshot, state.organization_id
      INTO current_revision, current_snapshot, current_org_id
    FROM public.proposal_option_states state
    WHERE state.client_id = p_client_id
    FOR UPDATE;

    IF NOT FOUND THEN
        current_revision := 0;
        current_snapshot := '[]'::jsonb;
        SELECT organization_id INTO current_org_id
        FROM public.profiles
        WHERE id = current_user_id;

        INSERT INTO public.proposal_option_states (
            client_id, organization_id, revision, snapshot,
            updated_at, updated_by, updated_device_id
        )
        VALUES (
            p_client_id, current_org_id, 0, current_snapshot,
            now(), current_user_id, p_device_id
        );
    END IF;

    IF current_org_id IS NULL THEN
        SELECT organization_id INTO current_org_id
        FROM public.profiles
        WHERE id = current_user_id;
    END IF;

    IF COALESCE(p_expected_revision, 0) <> current_revision THEN
        RETURN jsonb_build_object(
            'status', 'conflict',
            'revision', current_revision,
            'snapshot', current_snapshot
        );
    END IF;

    next_revision := current_revision + 1;

    UPDATE public.proposal_option_states
    SET revision = next_revision,
        snapshot = p_snapshot,
        organization_id = COALESCE(organization_id, current_org_id),
        updated_at = now(),
        updated_by = current_user_id,
        updated_device_id = p_device_id
    WHERE client_id = p_client_id;

    INSERT INTO public.proposal_option_history (
        client_id, organization_id, revision, snapshot,
        created_at, created_by, source_device_id
    )
    VALUES (
        p_client_id, current_org_id, next_revision, p_snapshot,
        now(), current_user_id, p_device_id
    )
    ON CONFLICT (client_id, revision) DO NOTHING;

    -- Mantém a tabela antiga compatível com telas ainda não atualizadas. A
    -- configuração local impede que o gatilho legado crie outra revisão.
    PERFORM set_config('app.proposal_snapshot_rpc', '1', true);

    DELETE FROM public.proposal_options
    WHERE client_id = p_client_id;

    FOR option_value IN SELECT value FROM jsonb_array_elements(p_snapshot)
    LOOP
        INSERT INTO public.proposal_options (
            user_id,
            organization_id,
            client_id,
            name,
            measurements,
            general_discount
        )
        VALUES (
            current_user_id,
            current_org_id,
            p_client_id,
            COALESCE(option_value->>'name', 'Opcao 1'),
            COALESCE(option_value->'measurements', '[]'::jsonb),
            COALESCE(option_value->'generalDiscount', '{}'::jsonb)
        );
    END LOOP;

    UPDATE public.clients
    SET last_updated = now()
    WHERE id = p_client_id;

    RETURN jsonb_build_object(
        'status', 'saved',
        'revision', next_revision
    );
END;
$$;

REVOKE ALL ON FUNCTION public.save_proposal_options_snapshot(bigint, jsonb, bigint, text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.save_proposal_options_snapshot(bigint, jsonb, bigint, text) TO authenticated;

-- Aplica somente os campos alterados pelo aparelho. O snapshot continua sendo
-- a fonte canônica, mas deixa de trafegar inteiro a cada pequena edição.
CREATE OR REPLACE FUNCTION public.apply_proposal_operations(
    p_snapshot jsonb,
    p_operations jsonb
)
RETURNS jsonb
LANGUAGE plpgsql
IMMUTABLE
AS $$
DECLARE
    result_snapshot jsonb := COALESCE(p_snapshot, '[]'::jsonb);
    operation_value jsonb;
    operation_type text;
    option_id text;
    measurement_id text;
    option_value jsonb;
    option_payload jsonb;
    measurement_payload jsonb;
    updated_option jsonb;
    updated_measurements jsonb;
BEGIN
    IF jsonb_typeof(result_snapshot) <> 'array' THEN
        RAISE EXCEPTION 'Snapshot de medidas deve ser um array';
    END IF;

    IF jsonb_typeof(p_operations) <> 'array' THEN
        RAISE EXCEPTION 'Operacoes de medidas devem ser um array';
    END IF;

    FOR operation_value IN SELECT value FROM jsonb_array_elements(p_operations)
    LOOP
        operation_type := operation_value->>'type';
        option_id := operation_value->>'optionId';

        CASE operation_type
            WHEN 'upsert_option' THEN
                option_payload := operation_value->'option';
                IF jsonb_typeof(option_payload) <> 'object' OR option_id IS NULL THEN
                    RAISE EXCEPTION 'Operacao upsert_option invalida';
                END IF;

                option_value := NULL;
                SELECT item.value INTO option_value
                FROM jsonb_array_elements(result_snapshot) item
                WHERE item.value->>'id' = option_id
                LIMIT 1;

                IF option_value IS NULL THEN
                    updated_option := option_payload
                        || jsonb_build_object('id', operation_value->'optionId')
                        || jsonb_build_object('measurements', '[]'::jsonb);
                    result_snapshot := result_snapshot || jsonb_build_array(updated_option);
                ELSE
                    updated_option := option_value
                        || option_payload
                        || jsonb_build_object('id', option_value->'id')
                        || jsonb_build_object(
                            'measurements',
                            COALESCE(option_value->'measurements', '[]'::jsonb)
                        );

                    SELECT COALESCE(
                        jsonb_agg(
                            CASE
                                WHEN item.value->>'id' = option_id THEN updated_option
                                ELSE item.value
                            END
                            ORDER BY item.ordinality
                        ),
                        '[]'::jsonb
                    )
                    INTO result_snapshot
                    FROM jsonb_array_elements(result_snapshot) WITH ORDINALITY item(value, ordinality);
                END IF;

            WHEN 'delete_option' THEN
                IF option_id IS NULL THEN
                    RAISE EXCEPTION 'Operacao delete_option invalida';
                END IF;

                SELECT COALESCE(jsonb_agg(item.value ORDER BY item.ordinality), '[]'::jsonb)
                INTO result_snapshot
                FROM jsonb_array_elements(result_snapshot) WITH ORDINALITY item(value, ordinality)
                WHERE item.value->>'id' <> option_id;

            WHEN 'upsert_measurement' THEN
                measurement_payload := operation_value->'measurement';
                measurement_id := measurement_payload->>'id';
                IF option_id IS NULL
                   OR jsonb_typeof(measurement_payload) <> 'object'
                   OR measurement_id IS NULL THEN
                    RAISE EXCEPTION 'Operacao upsert_measurement invalida';
                END IF;

                option_value := NULL;
                SELECT item.value INTO option_value
                FROM jsonb_array_elements(result_snapshot) item
                WHERE item.value->>'id' = option_id
                LIMIT 1;

                IF option_value IS NULL THEN
                    RAISE EXCEPTION 'Opcao % nao existe para receber a medida', option_id;
                END IF;

                IF EXISTS (
                    SELECT 1
                    FROM jsonb_array_elements(COALESCE(option_value->'measurements', '[]'::jsonb)) measurement
                    WHERE measurement.value->>'id' = measurement_id
                ) THEN
                    SELECT COALESCE(
                        jsonb_agg(
                            CASE
                                WHEN measurement.value->>'id' = measurement_id THEN measurement_payload
                                ELSE measurement.value
                            END
                            ORDER BY measurement.ordinality
                        ),
                        '[]'::jsonb
                    )
                    INTO updated_measurements
                    FROM jsonb_array_elements(COALESCE(option_value->'measurements', '[]'::jsonb))
                        WITH ORDINALITY measurement(value, ordinality);
                ELSE
                    updated_measurements := COALESCE(option_value->'measurements', '[]'::jsonb)
                        || jsonb_build_array(measurement_payload);
                END IF;

                updated_option := jsonb_set(option_value, '{measurements}', updated_measurements, true);
                SELECT COALESCE(
                    jsonb_agg(
                        CASE
                            WHEN item.value->>'id' = option_id THEN updated_option
                            ELSE item.value
                        END
                        ORDER BY item.ordinality
                    ),
                    '[]'::jsonb
                )
                INTO result_snapshot
                FROM jsonb_array_elements(result_snapshot) WITH ORDINALITY item(value, ordinality);

            WHEN 'delete_measurement' THEN
                measurement_id := operation_value->>'measurementId';
                IF option_id IS NULL OR measurement_id IS NULL THEN
                    RAISE EXCEPTION 'Operacao delete_measurement invalida';
                END IF;

                option_value := NULL;
                SELECT item.value INTO option_value
                FROM jsonb_array_elements(result_snapshot) item
                WHERE item.value->>'id' = option_id
                LIMIT 1;

                IF option_value IS NOT NULL THEN
                    SELECT COALESCE(
                        jsonb_agg(measurement.value ORDER BY measurement.ordinality),
                        '[]'::jsonb
                    )
                    INTO updated_measurements
                    FROM jsonb_array_elements(COALESCE(option_value->'measurements', '[]'::jsonb))
                        WITH ORDINALITY measurement(value, ordinality)
                    WHERE measurement.value->>'id' <> measurement_id;

                    updated_option := jsonb_set(option_value, '{measurements}', updated_measurements, true);
                    SELECT COALESCE(
                        jsonb_agg(
                            CASE
                                WHEN item.value->>'id' = option_id THEN updated_option
                                ELSE item.value
                            END
                            ORDER BY item.ordinality
                        ),
                        '[]'::jsonb
                    )
                    INTO result_snapshot
                    FROM jsonb_array_elements(result_snapshot) WITH ORDINALITY item(value, ordinality);
                END IF;

            WHEN 'set_option_order' THEN
                IF jsonb_typeof(operation_value->'optionIds') <> 'array' THEN
                    RAISE EXCEPTION 'Operacao set_option_order invalida';
                END IF;

                SELECT COALESCE(
                    jsonb_agg(ordered.value ORDER BY ordered.requested_position, ordered.original_position),
                    '[]'::jsonb
                )
                INTO result_snapshot
                FROM (
                    SELECT
                        item.value,
                        item.ordinality AS original_position,
                        COALESCE(
                            (
                                SELECT requested.ordinality
                                FROM jsonb_array_elements(operation_value->'optionIds')
                                    WITH ORDINALITY requested(value, ordinality)
                                WHERE requested.value::text = item.value->>'id'
                                LIMIT 1
                            ),
                            1000000000 + item.ordinality
                        ) AS requested_position
                    FROM jsonb_array_elements(result_snapshot)
                        WITH ORDINALITY item(value, ordinality)
                ) ordered;

            WHEN 'set_measurement_order' THEN
                IF option_id IS NULL
                   OR jsonb_typeof(operation_value->'measurementIds') <> 'array' THEN
                    RAISE EXCEPTION 'Operacao set_measurement_order invalida';
                END IF;

                option_value := NULL;
                SELECT item.value INTO option_value
                FROM jsonb_array_elements(result_snapshot) item
                WHERE item.value->>'id' = option_id
                LIMIT 1;

                IF option_value IS NOT NULL THEN
                    SELECT COALESCE(
                        jsonb_agg(ordered.value ORDER BY ordered.requested_position, ordered.original_position),
                        '[]'::jsonb
                    )
                    INTO updated_measurements
                    FROM (
                        SELECT
                            measurement.value,
                            measurement.ordinality AS original_position,
                            COALESCE(
                                (
                                    SELECT requested.ordinality
                                    FROM jsonb_array_elements(operation_value->'measurementIds')
                                        WITH ORDINALITY requested(value, ordinality)
                                    WHERE requested.value::text = measurement.value->>'id'
                                    LIMIT 1
                                ),
                                1000000000 + measurement.ordinality
                            ) AS requested_position
                        FROM jsonb_array_elements(COALESCE(option_value->'measurements', '[]'::jsonb))
                            WITH ORDINALITY measurement(value, ordinality)
                    ) ordered;

                    updated_option := jsonb_set(option_value, '{measurements}', updated_measurements, true);
                    SELECT COALESCE(
                        jsonb_agg(
                            CASE
                                WHEN item.value->>'id' = option_id THEN updated_option
                                ELSE item.value
                            END
                            ORDER BY item.ordinality
                        ),
                        '[]'::jsonb
                    )
                    INTO result_snapshot
                    FROM jsonb_array_elements(result_snapshot) WITH ORDINALITY item(value, ordinality);
                END IF;

            ELSE
                RAISE EXCEPTION 'Tipo de operacao de medidas desconhecido: %', operation_type;
        END CASE;
    END LOOP;

    RETURN result_snapshot;
END;
$$;

REVOKE ALL ON FUNCTION public.apply_proposal_operations(jsonb, jsonb) FROM PUBLIC;

CREATE OR REPLACE FUNCTION public.apply_proposal_option_operations(
    p_client_id bigint,
    p_operations jsonb,
    p_expected_revision bigint,
    p_device_id text DEFAULT NULL
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, auth
AS $$
DECLARE
    current_revision bigint;
    current_snapshot jsonb;
    next_snapshot jsonb;
    next_revision bigint;
    current_user_id uuid := auth.uid();
    current_org_id uuid;
    option_value jsonb;
BEGIN
    IF current_user_id IS NULL THEN
        RAISE EXCEPTION 'Sessao nao autenticada';
    END IF;

    IF NOT public.can_access_proposal_client(p_client_id) THEN
        RAISE EXCEPTION 'Cliente nao autorizado';
    END IF;

    IF jsonb_typeof(p_operations) <> 'array' THEN
        RAISE EXCEPTION 'Operacoes de medidas devem ser um array';
    END IF;

    PERFORM pg_advisory_xact_lock(p_client_id);

    SELECT state.revision, state.snapshot, state.organization_id
      INTO current_revision, current_snapshot, current_org_id
    FROM public.proposal_option_states state
    WHERE state.client_id = p_client_id
    FOR UPDATE;

    IF NOT FOUND THEN
        current_revision := 0;
        current_snapshot := '[]'::jsonb;
        SELECT organization_id INTO current_org_id
        FROM public.profiles
        WHERE id = current_user_id;

        INSERT INTO public.proposal_option_states (
            client_id, organization_id, revision, snapshot,
            updated_at, updated_by, updated_device_id
        )
        VALUES (
            p_client_id, current_org_id, 0, current_snapshot,
            now(), current_user_id, p_device_id
        );
    END IF;

    IF current_org_id IS NULL THEN
        SELECT organization_id INTO current_org_id
        FROM public.profiles
        WHERE id = current_user_id;
    END IF;

    IF COALESCE(p_expected_revision, 0) <> current_revision THEN
        RETURN jsonb_build_object(
            'status', 'conflict',
            'revision', current_revision,
            'snapshot', current_snapshot
        );
    END IF;

    IF jsonb_array_length(p_operations) = 0 THEN
        RETURN jsonb_build_object(
            'status', 'saved',
            'revision', current_revision,
            'snapshot', current_snapshot,
            'operationCount', 0
        );
    END IF;

    next_snapshot := public.apply_proposal_operations(current_snapshot, p_operations);
    next_revision := current_revision + 1;

    UPDATE public.proposal_option_states
    SET revision = next_revision,
        snapshot = next_snapshot,
        organization_id = COALESCE(organization_id, current_org_id),
        updated_at = now(),
        updated_by = current_user_id,
        updated_device_id = p_device_id
    WHERE client_id = p_client_id;

    INSERT INTO public.proposal_option_history (
        client_id, organization_id, revision, snapshot,
        created_at, created_by, source_device_id
    )
    VALUES (
        p_client_id, current_org_id, next_revision, next_snapshot,
        now(), current_user_id, p_device_id
    )
    ON CONFLICT (client_id, revision) DO NOTHING;

    -- Compatibilidade temporária com telas antigas do PWA.
    PERFORM set_config('app.proposal_snapshot_rpc', '1', true);

    DELETE FROM public.proposal_options
    WHERE client_id = p_client_id;

    FOR option_value IN SELECT value FROM jsonb_array_elements(next_snapshot)
    LOOP
        INSERT INTO public.proposal_options (
            user_id,
            organization_id,
            client_id,
            name,
            measurements,
            general_discount
        )
        VALUES (
            current_user_id,
            current_org_id,
            p_client_id,
            COALESCE(option_value->>'name', 'Opcao 1'),
            COALESCE(option_value->'measurements', '[]'::jsonb),
            COALESCE(option_value->'generalDiscount', '{}'::jsonb)
        );
    END LOOP;

    UPDATE public.clients
    SET last_updated = now()
    WHERE id = p_client_id;

    RETURN jsonb_build_object(
        'status', 'saved',
        'revision', next_revision,
        'snapshot', next_snapshot,
        'operationCount', jsonb_array_length(p_operations)
    );
END;
$$;

REVOKE ALL ON FUNCTION public.apply_proposal_option_operations(bigint, jsonb, bigint, text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.apply_proposal_option_operations(bigint, jsonb, bigint, text) TO authenticated;

COMMENT ON TABLE public.proposal_option_history IS
'Histórico imutável das medidas para recuperação e auditoria entre aparelhos.';

COMMENT ON FUNCTION public.save_proposal_options_snapshot(bigint, jsonb, bigint, text) IS
'Salva medidas atomicamente e rejeita snapshots baseados em uma revisão antiga.';

COMMENT ON FUNCTION public.apply_proposal_option_operations(bigint, jsonb, bigint, text) IS
'Aplica em lote somente as medidas e metadados alterados, com revisão e histórico.';

NOTIFY pgrst, 'reload schema';
