-- Portal publico de propostas: links com validade, decisoes e conversa.
-- Aplicar manualmente no SQL Editor do Supabase antes de publicar a interface.

CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS proposal_portals (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    token text NOT NULL UNIQUE DEFAULT encode(gen_random_bytes(24), 'hex'),
    organization_id uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
    client_id integer NOT NULL REFERENCES clients(id) ON DELETE CASCADE,
    created_by uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    expires_at timestamptz NOT NULL,
    status text NOT NULL DEFAULT 'active'
        CHECK (status IN ('active', 'approved', 'rejected', 'negotiating', 'expired', 'revoked')),
    decision_pdf_id integer REFERENCES saved_pdfs(id) ON DELETE SET NULL,
    decision_at timestamptz,
    view_count integer NOT NULL DEFAULT 0,
    first_viewed_at timestamptz,
    last_viewed_at timestamptz,
    last_activity_at timestamptz NOT NULL DEFAULT now(),
    last_read_by_company_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS proposal_portal_items (
    portal_id uuid NOT NULL REFERENCES proposal_portals(id) ON DELETE CASCADE,
    saved_pdf_id integer NOT NULL REFERENCES saved_pdfs(id) ON DELETE CASCADE,
    position integer NOT NULL DEFAULT 0,
    PRIMARY KEY (portal_id, saved_pdf_id)
);

CREATE TABLE IF NOT EXISTS proposal_portal_messages (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    portal_id uuid NOT NULL REFERENCES proposal_portals(id) ON DELETE CASCADE,
    saved_pdf_id integer REFERENCES saved_pdfs(id) ON DELETE SET NULL,
    sender_type text NOT NULL CHECK (sender_type IN ('client', 'company')),
    kind text NOT NULL DEFAULT 'message'
        CHECK (kind IN ('message', 'approved', 'rejected', 'negotiation')),
    body text,
    offer_type text CHECK (offer_type IS NULL OR offer_type IN ('percentage', 'fixed')),
    offer_value numeric CHECK (offer_value IS NULL OR offer_value >= 0),
    created_by uuid REFERENCES auth.users(id) ON DELETE SET NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    CHECK (kind = 'message' OR saved_pdf_id IS NOT NULL)
);

CREATE INDEX IF NOT EXISTS proposal_portals_org_activity_idx
    ON proposal_portals (organization_id, last_activity_at DESC);
CREATE INDEX IF NOT EXISTS proposal_portal_messages_portal_idx
    ON proposal_portal_messages (portal_id, created_at);

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_publication_tables
        WHERE pubname = 'supabase_realtime'
          AND schemaname = 'public'
          AND tablename = 'proposal_portal_messages'
    ) THEN
        ALTER PUBLICATION supabase_realtime ADD TABLE proposal_portal_messages;
    END IF;
END $$;

ALTER TABLE proposal_portals ENABLE ROW LEVEL SECURITY;
ALTER TABLE proposal_portal_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE proposal_portal_messages ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS proposal_portals_company_all ON proposal_portals;
CREATE POLICY proposal_portals_company_all ON proposal_portals
FOR ALL TO authenticated
USING (organization_id = (SELECT organization_id FROM profiles WHERE id = auth.uid()))
WITH CHECK (organization_id = (SELECT organization_id FROM profiles WHERE id = auth.uid()));

DROP POLICY IF EXISTS proposal_portal_items_company_all ON proposal_portal_items;
CREATE POLICY proposal_portal_items_company_all ON proposal_portal_items
FOR ALL TO authenticated
USING (
    EXISTS (
        SELECT 1 FROM proposal_portals p
        WHERE p.id = portal_id
          AND p.organization_id = (SELECT organization_id FROM profiles WHERE id = auth.uid())
    )
)
WITH CHECK (
    EXISTS (
        SELECT 1 FROM proposal_portals p
        WHERE p.id = portal_id
          AND p.organization_id = (SELECT organization_id FROM profiles WHERE id = auth.uid())
    )
);

DROP POLICY IF EXISTS proposal_portal_messages_company_all ON proposal_portal_messages;
CREATE POLICY proposal_portal_messages_company_all ON proposal_portal_messages
FOR ALL TO authenticated
USING (
    EXISTS (
        SELECT 1 FROM proposal_portals p
        WHERE p.id = portal_id
          AND p.organization_id = (SELECT organization_id FROM profiles WHERE id = auth.uid())
    )
)
WITH CHECK (
    sender_type = 'company'
    AND created_by = auth.uid()
    AND EXISTS (
        SELECT 1 FROM proposal_portals p
        WHERE p.id = portal_id
          AND p.organization_id = (SELECT organization_id FROM profiles WHERE id = auth.uid())
    )
);

CREATE OR REPLACE FUNCTION create_proposal_portal(
    p_pdf_ids integer[],
    p_expires_at timestamptz
)
RETURNS TABLE (portal_id uuid, portal_token text, expires_at timestamptz)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, auth
AS $$
DECLARE
    v_org_id uuid;
    v_client_id integer;
    v_portal proposal_portals%ROWTYPE;
BEGIN
    IF auth.uid() IS NULL THEN
        RAISE EXCEPTION 'Usuario nao autenticado';
    END IF;

    IF p_pdf_ids IS NULL OR cardinality(p_pdf_ids) = 0 THEN
        RAISE EXCEPTION 'Selecione pelo menos uma proposta';
    END IF;

    IF p_expires_at <= now() THEN
        RAISE EXCEPTION 'A validade precisa estar no futuro';
    END IF;

    SELECT organization_id INTO v_org_id FROM profiles WHERE id = auth.uid();
    IF v_org_id IS NULL THEN
        RAISE EXCEPTION 'Organizacao nao encontrada';
    END IF;

    SELECT min(sp.client_id) INTO v_client_id
    FROM saved_pdfs sp
    JOIN profiles owner_profile ON owner_profile.id = sp.user_id
    WHERE sp.id = ANY(p_pdf_ids)
      AND owner_profile.organization_id = v_org_id;

    IF v_client_id IS NULL OR (
        SELECT count(*) FROM saved_pdfs sp
        JOIN profiles owner_profile ON owner_profile.id = sp.user_id
        WHERE sp.id = ANY(p_pdf_ids)
          AND sp.client_id = v_client_id
          AND owner_profile.organization_id = v_org_id
    ) <> cardinality(p_pdf_ids) THEN
        RAISE EXCEPTION 'As propostas precisam pertencer ao mesmo cliente e organizacao';
    END IF;

    INSERT INTO proposal_portals (organization_id, client_id, created_by, expires_at)
    VALUES (v_org_id, v_client_id, auth.uid(), p_expires_at)
    RETURNING * INTO v_portal;

    INSERT INTO proposal_portal_items (portal_id, saved_pdf_id, position)
    SELECT v_portal.id, pdf_id, ordinality::integer - 1
    FROM unnest(p_pdf_ids) WITH ORDINALITY AS selected(pdf_id, ordinality);

    RETURN QUERY SELECT v_portal.id, v_portal.token, v_portal.expires_at;
END;
$$;

GRANT EXECUTE ON FUNCTION create_proposal_portal(integer[], timestamptz) TO authenticated;

NOTIFY pgrst, 'reload schema';
